server:
  port: 8087
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    db1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vue?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123456
    db2:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/home?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123456

#mybatis查询日志，可以打印出查询的sql,parameters
#springboot+mybatis日志显示SQL:在yml配置文件中添加下面的配置。
#需要注意的是，com.tom.login_boot.mapper为自己项目中mapper接口的路径。
#这种方式也同时支持mybatis-plus。
logging:
  level:
    com.tom.login_boot.mapper: debug

jwt:
  secretKey: login
#  expiredTime: 6000
#  时间：十天
  expiredTime: 864000


# 腾讯云文件服务器
# 参考路径：https://cloud.tencent.com/document/product/436/10199

